name: Distribute Android Build to Firebase

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release


      - name: Upload and Distribute App
        uses: mastersam07/firebase-app-distribution-action@v0.1
        with:
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          appId: ${{ secrets.FIREBASE_APP_ID }}
          file: './build/app/outputs/flutter-apk/app-release.apk'  # e.g., './build/app/outputs/flutter-apk/app-release.apk'
          groups: 'internal-testers'
#
#      - name: Upload to Firebase App Distribution
#        run: |
#          npm install -g firebase-tools
#          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
#            --app islami-app-fue \
#            --token "${{ secrets.FIREBASE_TOKEN }}" \
#            --groups "internal-testers"